<a href="https://colab.research.google.com/github/Neenz-123/Physiopro/blob/main/Laptop_pricing_dataset_coursera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
url= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_base.csv"

In [4]:
df=pd.read_csv(url)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Acer       237 non-null    object
 1   4          237 non-null    int64
 2   IPS Panel  237 non-null    object
 3   2          237 non-null    int64
 4   1          237 non-null    int64
 5   5          237 non-null    int64
 6   35.56      237 non-null    object
 7   1.6        237 non-null    float64
 8   8          237 non-null    int64
 9   256        237 non-null    int64
 10  1.6.1      237 non-null    object
 11  978        237 non-null    int64
dtypes: float64(1), int64(7), object(4)
memory usage: 22.3+ KB

In [6]:
df.head()

   Acer  4  IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1   978
0  Dell  3    Full HD  1  1  3  39.624  2.0  4  256   2.2   634
1  Dell  3    Full HD  1  1  7  39.624  2.7  8  256   2.2   946
2  Dell  4  IPS Panel  2  1  5  33.782  1.6  8  128  1.22  1244
3    HP  4    Full HD  2  1  7  39.624  1.8  8  256  1.91   837
4  Dell  3    Full HD  1  1  5  39.624  1.6  8  256   2.2  1016

In [7]:
print(df.head)

<bound method NDFrame.head of         Acer  4  IPS Panel  2  1  5   35.56  1.6  8  256 1.6.1   978
0       Dell  3    Full HD  1  1  3  39.624  2.0  4  256   2.2   634
1       Dell  3    Full HD  1  1  7  39.624  2.7  8  256   2.2   946
2       Dell  4  IPS Panel  2  1  5  33.782  1.6  8  128  1.22  1244
3         HP  4    Full HD  2  1  7  39.624  1.8  8  256  1.91   837
4       Dell  3    Full HD  1  1  5  39.624  1.6  8  256   2.2  1016
..       ... ..        ... .. .. ..     ...  ... ..  ...   ...   ...
232   Lenovo  4  IPS Panel  2  1  7   35.56  2.6  8  256   1.7  1891
233  Toshiba  3    Full HD  2  1  5  33.782  2.4  8  256   1.2  1950
234   Lenovo  4  IPS Panel  2  1  5   30.48  2.6  8  256  1.36  2236
235   Lenovo  3    Full HD  3  1  5  39.624  2.5  6  256   2.4   883
236  Toshiba  3    Full HD  2  1  5   35.56  2.3  8  256  1.95  1499

[237 rows x 12 columns]>

In [12]:
headers=[ "Manufacturer", "Category", "Screen", "GPU", "OS", "CPU_core", "Screen_Size_inch", "CPU_frequency", "RAM_GB", "Storage_GB_SSD", "Weight_kg", "Price"]

In [14]:
df.columns= headers
df.head(5)

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634
1,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.2,946
2,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
3,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
4,Dell,3,Full HD,1,1,5,39.624,1.6,8,256,2.2,1016

In [15]:
df.tail(25)

,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
212,HP,3,Full HD,2,1,5,39.624,2.5,4,256,2.04,1066
213,HP,3,Full HD,2,1,5,35.56,2.5,4,128,1.95,1607
214,Samsung,4,Full HD,2,1,7,38.1,2.7,8,256,1.17,2158
215,Lenovo,4,IPS Panel,2,1,5,35.56,2.5,8,256,1.32,2285
216,Toshiba,3,Full HD,2,1,5,33.782,2.5,8,256,1.05,1874
217,Dell,3,Full HD,2,1,5,35.56,2.8,8,256,1.6,1531
218,Lenovo,3,Full HD,3,1,7,39.624,2.7,6,256,2.2,1002
219,HP,3,Full HD,3,1,7,39.624,2.7,8,256,2.04,1294
220,Lenovo,3,Full HD,2,1,5,33.782,2.5,4,128,1.44,1119
221,HP,3,Full HD,2,1,5,33.782,2.5,8,256,1.49,1219
222,HP,4,Full HD,1,1,7,39.624,2.5,8,256,1.84,1648
223,Toshiba,3,IPS Panel,3,1,7,38.1,2.6,16,256,2.4,2509
224,Lenovo,4,IPS Panel,2,1,7,30.48,2.7,8,256,1.36,2096
225,HP,3,Full HD,2,1,5,39.624,2.3,8,256,2.31,1480
226,Toshiba,3,IPS Panel,2,1,5,35.56,2.3,4,128,1.47,1404
227,HP,2,Full HD,2,1,5,31.75,2.3,8,256,1.26,2120
228,Dell,4,Full HD,2,1,5,35.56,2.5,8,256,1.36,2082
229,Dell,4,Full HD,2,1,5,?,2.5,8,256,1.36,1870
230,Dell,4,Full HD,2,1,7,35.56,2.8,8,256,1.36,2255
231,Toshiba,3,Full HD,2,1,5,33.782,2.3,8,256,1.2,1855
232,Lenovo,4,IPS Panel,2,1,7,35.56,2.6,8,256,1.7,1891
233,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.2,1950
234,Lenovo,4,IPS Panel,2,1,5,30.48,2.6,8,256,1.36,2236
235,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.4,883
236,Toshiba,3,Full HD,2,1,5,35.56,2.3,8,256,1.95,1499

In [18]:
df.replace('?', np.nan, inplace=True)
print(df.dtypes)

Manufacturer         object
Category              int64
Screen               object
GPU                   int64
OS                    int64
CPU_core              int64
Screen_Size_inch     object
CPU_frequency       float64
RAM_GB                int64
Storage_GB_SSD        int64
Weight_kg            object
Price                 int64
dtype: object

In [19]:
print(df.describe())

         Category         GPU          OS    CPU_core  CPU_frequency  \
count  237.000000  237.000000  237.000000  237.000000     237.000000
mean     3.202532    2.151899    1.059072    5.632911       2.363291
std      0.776450    0.639556    0.236258    1.243736       0.409271
min      1.000000    1.000000    1.000000    3.000000       1.200000
25%      3.000000    2.000000    1.000000    5.000000       2.000000
50%      3.000000    2.000000    1.000000    5.000000       2.500000
75%      4.000000    3.000000    1.000000    7.000000       2.700000
max      5.000000    3.000000    2.000000    7.000000       2.900000

           RAM_GB  Storage_GB_SSD        Price
count  237.000000      237.000000   237.000000
mean     7.881857      245.738397  1464.388186
std      2.487845       34.832516   574.956374
min      4.000000      128.000000   527.000000
25%      8.000000      256.000000  1068.000000
50%      8.000000      256.000000  1333.000000
75%      8.000000      256.000000  1777.000000
max     16.000000      256.000000  3810.000000

In [20]:
print(df.describe(include='all'))

       Manufacturer    Category   Screen         GPU          OS    CPU_core  \
count           237  237.000000      237  237.000000  237.000000  237.000000
unique           11         NaN        2         NaN         NaN         NaN
top            Dell         NaN  Full HD         NaN         NaN         NaN
freq             71         NaN      161         NaN         NaN         NaN
mean            NaN    3.202532      NaN    2.151899    1.059072    5.632911
std             NaN    0.776450      NaN    0.639556    0.236258    1.243736
min             NaN    1.000000      NaN    1.000000    1.000000    3.000000
25%             NaN    3.000000      NaN    2.000000    1.000000    5.000000
50%             NaN    3.000000      NaN    2.000000    1.000000    5.000000
75%             NaN    4.000000      NaN    3.000000    1.000000    7.000000
max             NaN    5.000000      NaN    3.000000    2.000000    7.000000

       Screen_Size_inch  CPU_frequency      RAM_GB  Storage_GB_SSD Weight_kg  \
count               233     237.000000  237.000000      237.000000       232
unique                9            NaN         NaN             NaN        77
top              39.624            NaN         NaN             NaN       2.2
freq                 89            NaN         NaN             NaN        21
mean                NaN       2.363291    7.881857      245.738397       NaN
std                 NaN       0.409271    2.487845       34.832516       NaN
min                 NaN       1.200000    4.000000      128.000000       NaN
25%                 NaN       2.000000    8.000000      256.000000       NaN
50%                 NaN       2.500000    8.000000      256.000000       NaN
75%                 NaN       2.700000    8.000000      256.000000       NaN
max                 NaN       2.900000   16.000000      256.000000       NaN

              Price
count    237.000000
unique          NaN
top             NaN
freq            NaN
mean    1464.388186
std      574.956374
min      527.000000
25%     1068.000000
50%     1333.000000
75%     1777.000000
max     3810.000000

In [23]:
df['Screen_Size_inch'] = pd.to_numeric(df['Screen_Size_inch'], errors='coerce')
print(df.dtypes)

Manufacturer         object
Category              int64
Screen               object
GPU                   int64
OS                    int64
CPU_core              int64
Screen_Size_inch    float64
CPU_frequency       float64
RAM_GB                int64
Storage_GB_SSD        int64
Weight_kg           float64
Price                 int64
dtype: object

In [28]:
df['Weight_kg'] = pd.to_numeric(df['Weight_kg'], errors='coerce')
print(df.dtypes)

Manufacturer         object
Category              int64
Screen               object
GPU                   int64
OS                    int64
CPU_core              int64
Screen_Size_inch    float64
CPU_frequency       float64
RAM_GB                int64
Storage_GB_SSD        int64
Weight_kg           float64
Price                 int64
dtype: object

In [29]:
print('Missing values after type conversion:')
print(df.isnull().sum())

Missing values after type conversion:
Manufacturer        0
Category            0
Screen              0
GPU                 0
OS                  0
CPU_core            0
Screen_Size_inch    4
CPU_frequency       0
RAM_GB              0
Storage_GB_SSD      0
Weight_kg           5
Price               0
dtype: int64

In [30]:
print('\nUpdated descriptive statistics:')
print(df.describe(include='all'))

Updated descriptive statistics:
       Manufacturer    Category   Screen         GPU          OS    CPU_core  \
count           237  237.000000      237  237.000000  237.000000  237.000000
unique           11         NaN        2         NaN         NaN         NaN
top            Dell         NaN  Full HD         NaN         NaN         NaN
freq             71         NaN      161         NaN         NaN         NaN
mean            NaN    3.202532      NaN    2.151899    1.059072    5.632911
std             NaN    0.776450      NaN    0.639556    0.236258    1.243736
min             NaN    1.000000      NaN    1.000000    1.000000    3.000000
25%             NaN    3.000000      NaN    2.000000    1.000000    5.000000
50%             NaN    3.000000      NaN    2.000000    1.000000    5.000000
75%             NaN    4.000000      NaN    3.000000    1.000000    7.000000
max             NaN    5.000000      NaN    3.000000    2.000000    7.000000

        Screen_Size_inch  CPU_frequency      RAM_GB  Storage_GB_SSD  \
count         233.000000     237.000000  237.000000      237.000000
unique               NaN            NaN         NaN             NaN
top                  NaN            NaN         NaN             NaN
freq                 NaN            NaN         NaN             NaN
mean           37.276953       2.363291    7.881857      245.738397
std             2.975637       0.409271    2.487845       34.832516
min            30.480000       1.200000    4.000000      128.000000
25%            35.560000       2.000000    8.000000      256.000000
50%            38.100000       2.500000    8.000000      256.000000
75%            39.624000       2.700000    8.000000      256.000000
max            43.942000       2.900000   16.000000      256.000000

         Weight_kg        Price
count   232.000000   237.000000
unique         NaN          NaN
top            NaN          NaN
freq           NaN          NaN
mean      1.863362  1464.388186
std       0.495099   574.956374
min       0.810000   527.000000
25%       1.440000  1068.000000
50%       1.875000  1333.000000
75%       2.200000  1777.000000
max       3.600000  3810.000000

In [31]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Manufacturer      237 non-null    object
 1   Category          237 non-null    int64
 2   Screen            237 non-null    object
 3   GPU               237 non-null    int64
 4   OS                237 non-null    int64
 5   CPU_core          237 non-null    int64
 6   Screen_Size_inch  233 non-null    float64
 7   CPU_frequency     237 non-null    float64
 8   RAM_GB            237 non-null    int64
 9   Storage_GB_SSD    237 non-null    int64
 10  Weight_kg         232 non-null    float64
 11  Price             237 non-null    int64
dtypes: float64(3), int64(7), object(2)
memory usage: 22.3+ KB
None